name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# İş akışının izinleri
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    # Bu iş, en güncel Ubuntu sanal makinesinde çalışacak
    runs-on: ubuntu-latest
    # İşin adımları (Steps)
    steps:
      # 1. Adım: Kodlarımızı sanal makineye indiriyoruz (Checkout)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Temamız bir submodule olduğu için bu çok önemli!

      # 2. Adım: Hugo'yu kuruyoruz
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # 3. Adım: Sitemizi build ediyoruz
      - name: Build
        run: hugo --minify

      # 4. Adım: Build edilen dosyaları (artifact) GitHub'a yüklüyoruz ki yayınlama işi kullanabilsin
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # 'deploy' adında ikinci bir iş tanımlıyoruz
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Yayınlama adımları
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
